### ISSUE TITLE
Error when compiled with gcc 5

### ISSUE THREAD

**Issue by Panaetius** [deepsense-io/roi-pooling#1]
First off, a big thank you for making/open-sourcing this!

I had used the roi-pooling op before, but decided to go from the TF pip package to compiling it myself from source, which worked fine, but when I recompiled the roi-pooling, I got an error "undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv"

Google led me to https://github.com/GPflow/GPflow/issues/268 and in turn https://github.com/GPflow/GPflow/issues/227 

So after a bit of looking around the source, I saw the "-D _GLIBCXX_USE_CXX11_ABI=0" part in the roi_pooling/Makefile (lines 9 and 12) and after removing that, everything compiles and works as before.

Maybe you could say so in the README or adjust the Makefile to work with gcc4 and 5?

Thought I'd let you (and other future users) know, in case anyone else runs into this problem

Thanks again for a great plugin!

**Comment by tgrel** [comment]
Hi Panaetius!

Thanks for helping us improve our implementation :)

As for the compilation issue, solving it would be tricky since it would require checking what GCC version was TensorFlow compiled with. This can be done, but the solutions to this problem are not very portable and maintaining them seems quite costly.

I'm going to provide some information in the README and close the issue.

**Comment by abadcd** [comment]
@Panaetius @tgrel Hi, I have the same error, but it didn't work for me. My gcc version is 4.8.5. I want to know if this issue is related to the gcc version.

**Comment by Kevinlongran** [comment]
That's definitely related to the gcc version. It works for gcc 5 while fail when I use gcc4
